name: download
on:
  push:
    branches:
      - main
  
      


jobs:
  init:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vpc
    steps:
      - name: clone repo
        uses: actions/checkout@v4
        
      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}     
      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "us-west-2"
          role-to-assume: ${{ secrets.CI_ROLE }}
      - name: Configure Terraform credentials for JFrog
        run: |
          cat > ~/.terraformrc <<EOF
          credentials "trialxphjx0.jfrog.io" {
            token = "${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}"
          }
          EOF    
      - name: init
        run: terraform init
      - name: plan
        run: terraform plan              
