name: download
on:
  push:
    branches:
      - main
  
      

jobs:
  init:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vpc
    steps:
      - name: clone repo
        uses: actions/checkout@v4
        
      - uses: StudisCorporation/actions-setup-terraform-credentials@v1.0.0
        with:
          token: ${{ secrets.ARTFACTORY_ACCESS_TOKEN }}  
          hostname: ${{ secrets.JF_URL }}      
      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "us-west-2"
          role-to-assume: ${{ secrets.CI_ROLE }}
      - name: init
        run: terraform init
      - name: plan
        run: terraform plan              
